version: '2'

services:
  api:
    build: .
    restart: unless-stopped
    container_name: api
    ports:
      - "8080:9999"
    depends_on:
      - mariadb
    networks:
      - polytech

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=glopglop
      - MYSQL_DATABASE=eventmanager
      - MYSQL_USER=pifou
      - MYSQL_PASSWORD=pasglop
    networks:
      - polytech

networks:
  polytech:

volumes:
  mariadb: